const functions = require('firebase-functions');

// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
// exports.helloWorld = functions.https.onRequest((request, response) => {
//  response.send("Hello from Firebase!");
// });

const GoogleAssistant = require('./googleassistant');
const deviceCredentials = require('./devicecredentials.json');

const CREDENTIALS = {
	client_id: deviceCredentials.client_id,
	client_secret: deviceCredentials.client_secret,
	refresh_token: deviceCredentials.refresh_token,
	type: "authorized_user"
};

const assistant = new GoogleAssistant(CREDENTIALS);

let questions = [
	"Name ten body parts that your partner likes to kiss",
	"Say a list of 10 items or things you bought and never used or regretted buying",
	"If you were the opposite sex for one hour, what would you do?",
	"What was the most embarrassing moment of your life?",
	"Have you ever been humiliated? Explain what happened and how you felt",
	"Describe the strangest dream you’ve had in your life",
	"Which player would you like to swap lives with for a week?",
	"What physical feature do you get complimented on the most?",
	"What is that one thing you would never do even if someone offered you all of the money in the world?",
	"Among all the people in this room, which guy/girl would you like to date?",
	"Who in the room do you think would be a bad date?",
	"What is the quality or characteristic that would like to change about you?",
	"Have you fallen in love with a friend of your partner? Has anyone noticed?",
	"What do you think that your boyfriend/girlfriend thinks about marriage?",
	"What was the craziest thing that has happened to you in a mall?",
	"Mention the most annoying experience in some shopping.",
	"What is the meanest thing you have done in your life?",
	"Have you ever thought of cheat on your boyfriend/girlfriend?",
	"Have you ever lied to your partner to avoid an intimate moment, for example, say that you feel sick?",
	"What is the worst rumor or gossip you said or repeated and at the end was something wrong?",
	"What was the most disgusting joke ever played with someone?",
	"What’s your wildest fantasy?",
	"Have you ever peed in a pool?",
	"What is the most stupid thing you’ve done in front of a crowd?",
	"What’s the first thing you would do if you were invisible?",
	"Have you ever been hinted or has overstepped someone of the same sex? What happened, how did you react?",
	"Which of the players in this group considered to have the most sensual and daring clothes?",
	"Who do you think is the worst party dress? What would you recommend?",
	"You might think that someone of your friends or family made a terrible decision for life says who and what s/he did.",
	"Say who (here) has a wrong partner or does not suit him.",
	"If you were marooned on an island with one person whom you know personally, who would like it to be that person?",
	"He mentions something that ever done and that you did not want to be known",
	"What is the dumbest thing you’ve said your partner while on intimacy?",
	"Have you ever picked your nose and eaten it?",
	"Which of the people who are in this game, considered to have the best body?",
	"Which of the people who are in this game, believes it has lately deteriorated their physical appearance: his body, his dress?",
	"If you could suddenly become invisible, what more naughty things you like to do?",
	"What is your biggest fear in a relationship?",
	"What was your funniest first date ever?",
	"What is your biggest turn off in a partner?",
	"What is your weirdest habit?",
	"How many kids would you like to have?",
	"What is the perfect first day?",
	"What is one embarrassing fact I should know about you?",
	"What was your childhood nickname?",
	"What is your favourite movie?",
	"Describe your worst date ever?",
	"If there was no such thing as money, what would you do with your life?",
	"What is your favourite food?",
	"What are your three favourite colours, and why?",
	"What is your dream job?",
	"If you were trapped on an island for 3 days, what would you take with you?",
	"Who is your favourite person and why?",
	"Do you prefer apple or android?",
	"How do you put your toilet paper on the roll?",
	"What is your best talent?",
	"Do you believe in love at first sight?",
	"Do you believe in love at all?",
	"What is your dream wedding?",
	"Would you ever consider being a nudist?",
	"How do you feel about end pieces of a loaf of bread?",
	"Can you touch your tongue to your nose?",
	"If you could take away one bad thing in the world, what would it be?",
	"What is your guilty pleasure?",
	"What is the most exotic food that you have ever eaten?",
	"What country would like to live in if you had the chance?",
	"If you could change one thing on your body, what would it be?",
	"What do you daydream about the most?",
	"Describe the weirdest dream you’ve ever had?",
	"Can you lick your elbow?",
	"Is the dress Black and Blue or Gold and White?",
	"How do you feel about social media?",
	"What is your favourite season of the year?",
	"Could you go a week without junk food?",
	"How was your first kiss?",
	"Describe your worst kiss ever?",
	"Do you like to exercise?",
	"What was your first impression of your spouse?",
	"How soon did you realize that you were in love with your partner?",
	"Who is your favourite in-law?",
	"Who is your least favourite in-law?",
	"How many children would you like to have?",
	"Have you ever thought about marrying someone else?",
	"How many relationships have you had before your spouse?",
	"What is your partner’s most annoying habit?",
	"What is the sweetest thing your spouse has ever done for you?",
	"What is your favourite thing about your spouse?",
	"What can your spouse do/say to make you do anything?",
	"If you had never met your spouse where do you think you would be?",
	"What body part of your spouse does you like the most?",
	"What is the sexiest thing about your spouse?",
	"If you could fix one body part on your spouse, which would it be?",
	"Does your spouse act more like their mother or their father?",
	"Is your spouse a good dancer?",
	"What white lie have you told your partner to make sure not to hurt their feelings?",
	"How many days could you go without your spouse?",
	"What personality trait does you least like about your spouse?",
	"How soon did you want start a family?",
	"What country would you like to visit with your spouse?",
	"What is your spouse’s favourite colour?",
	"What is your spouse’s favourite sport’s team?",
	"What was your spouse’s childhood nickname?",
	"What could your spouse not go a day without?",
	"Would your spouse trade you for a million dollars?",
	"What is one lie your spouse tells everyone else, but you know the truth?",
	"Have you ever accused you spouse of cheating?",
	"How many times have you and your spouse broken up before you got married?",
	"Would you leave your spouse if it meant that you would be very rich?",
	"Who in your family likes your spouse the least, why?",
	"Has your spouse ever done something really embarrassing in public to the point that you did not want to be seen with them?",
	"What is your favourite color?",
	"What is your favourite animal?",
	"What is your favourite school subject?",
	"Who is your favourite teacher, and why?",
	"What is your favourite song?",
	"Who is your favourite Disney character?",
	"What is your favourite TV show?",
	"What is your pet’s name?",
	"What is your shoe size?",
	"Who is your favourite singer?",
	"Do you like bugs?",
	"What is your favourite vegetable?",
	"Would you rather be a chicken or duck?",
	"Would you rather be a pig or snake?",
	"What is your favourite game to play?",
	"Do you like doing chores?",
	"What is your favourite thing to do on the weekends?",
	"Do you know how to dance?",
	"Do you know how to cook?",
	"Can you speak a different language?",
	"What is your favourite thing to do after school?",
	"Are you in any sports?",
	"What is your favourite sport?",
	"What animal are you scared of?",
	"Are you scared of monsters?",
	"Do you have an imaginary friend?",
	"Who is your best friend?",
	"When did you learn how to ride a bike?",
	"Can you use a pogo stick?",
	"What do you want to be when you grow up?",
	"What is your favourite sport in the Olympics?",
	"What is the capital of the state that you live in?",
	"If you could go anywhere in the world, where would you go?",
	"If you a million dollars, what would you do with all of your money?",
	"If you could dye your hair any colour, what colour would you pick?",
	"How many brothers and sisters do you have?",
	"If you could be any animal, which one would you be?",
	"What is your favourite place to go out to eat?",
	"How people have you slept with on campus?",
	"What is your real GPA?",
	"What is your least favourite frat on campus?",
	"What did you do on your first night of freshman year?",
	"Would you ever have sex with one of your professors? If so, which one?",
	"Have you ever blacked out from drinking too much?",
	"What is the craziest thing that you have ever done while drunk?",
	"Who is the best roommate that you have ever had?",
	"What is the most annoying thing that your roommate has ever done?",
	"Have you ever had sex anywhere on campus?",
	"Have you ever had sex in your roommate’s bed?",
	"Did you smoke or drink before college? Or did you start when you got here?",
	"Have you ever been a stripper?",
	"Have you ever slept with your roommate’s bf/gf?",
	"Would you drop out of school if you were to win the lottery?",
	"What is the best party that you’ve ever been to?",
	"How many parties have you thrown at your house?",
	"What is most amount of shots that you have taken in one night?",
	"Have you ever thrown up in someone’s car?",
	"Have you ever wet bed from being too drunk?",
	"What is the longest you have gone without sleep?",
	"How many times have you skipped class for no reason?",
	"Have you ever gotten an STD?",
	"Have you ever woken up to a stranger in your bed?",
	"What is the earliest you have ever started drinking in the day?",
	"Have you ever spent your parent’s money on alcohol?",
	"How many freshmen have you slept with?",
	"Have you ever taken money from a freshman?",
	"Have you ever lied to your parents about if you were in classes or not?",
	"Have you ever taken money from your roommate?",
	"What is the most annoying thing your roommate does?",
	"Have you been in any fights while in school?",
	"Have you ever had someone write a paper for you?",
	"What is the most annoying thing that your mom does?",
	"What is the most annoying thing that your dad does?",
	"Have you ever snuck anyone into to the house?",
	"How many times have you snuck out of the house?",
	"What is the best dish that you mom makes for dinner?",
	"If you could change any of the house rules, what would it be?",
	"Would you rather be a horse or a cow?",
	"What is the funniest thing your grandparents have ever said?",
	"If you could get rid of one household chore, what would it be?",
	"What is your favourite cartoon from your generation?",
	"What is your favourite childhood song?",
	"What is your favourite board game to play with your family?",
	"If you could put one person in your family on mute for a day, who would it be?",
	"At what age did you learn to ride a bike?",
	"Do you know how to swim?",
	"What is the funniest dream that you have ever had?",
	"Have you ever had a dream about one of your relatives?",
	"Who is your celebrity husband or wife?",
	"Who taught you how to tie your shoes?",
	"What is the longest that you have ever been without taking a shower?",
	"Have you ever worn the same clothes for more than three days?",
	"What is your favourite holiday and why?",
	"If you could be any dinosaur, which would it be?",
	"How long could you without eating your favourite food?",
	"Who in your family tells the corniest jokes?",
	"Would you rather be a bumblebee or a slug?",
	"Have you ever eaten a worm?",
	"Have you ever picked your nose when you thought no one was looking?",
	"If you could be any super villain, who would you be?",
	"Who is your best looking teacher that you have ever had?",
	"Have you ever cheated on any test?",
	"Who is your crush at school?",
	"Who is the most annoying person you know?",
	"Have you ever pulled a prank on your teacher?",
	"Have you ever lied to your parents about what you were doing after school?",
	"Have you ever blamed something that you have done on one of your siblings?",
	"What college do you plan on going to?",
	"Are you still a virgin?",
	"How many boyfriends (or girlfriends) have you had?",
	"Have you ever been kissed yet? If so, who was your best kiss?",
	"What is your biggest pet peeve?",
	"What is the best vacation you’ve ever been on?",
	"Have you ever told one of your best friend’s secrets, even if you said you wouldn’t?",
	"Have you ever had a crush on someone that your best friend has dated?",
	"What is the most annoying thing that one of your siblings has done?",
	"Do you have a job? If so, what is your favourite thing about it?",
	"If you were a billionaire, what would you spend your time doing?",
	"What is the longest time you have ever been grounded?",
	"What is the longest time that you think you could go without your cell phone?",
	"What is the most expensive thing you own?",
	"If you had the choice to live on your own right now, would you do it?",
	"Can you see yourself being married to the creepiest kid a your school someday?",
	"Would you ever get on a dating website?",
	"Have you ever watched an adult film without your parents knowing?",
	"If you could own your own business one day, what would it be?",
	"What is your favourite kind of clothing?",
	"What celebrity are you obsessed with?",
	"What is the funniest youtube video you have ever seen?",
	"Who is the worst teacher you have ever had, why?",
	"What is your favourite sports team?",
	"If animals could talk, which one would you have a conversation with?",
	"What is your favorite restaurant?",
	"What makes you cry?",
	"What makes you laugh?",
	"What is something you find absolutely disgusting?",
	"Have you ever been stuck in an elevator and if so who were you with?",
	"Have you ever been on an airplane and if so where were you going?",
	"Who was your favorite teacher in school?",
	"What was your favorite subject in school?",
	"What is something that you are not looking forward to?",
	"Knowing now what you didn’t know then, what would you have done differently?",
	"Have you ever told a secret after you were told not to?",
	"Are you always on time, or are you always late?",
	"Are you a morning person or a night person?",
	"What is one job you would never want to do?",
	"What is your favorite ice cream flavor?",
	"When you think that no one is listening, do you sing in the shower?",
	"The last time you argued with someone, did you apologize first or was it the other person?",
	"What is your favorite food?",
	"What is the best gift you ever received?",
	"What was your favorite childhood toy?",
	"If you were given a million dollars, what would you do with it?",
	"Have you ever been arrested?",
	"What is your favorite sport?",
	"Have you ever been golfing?",
	"Have you ever played tennis?",
	"What is your favorite ride at the amusement park?",
	"Do you prefer the beach or the mountains?",
	"Have you ever been on a train?",
	"If you found a large amount of money, would you keep it or would you try to find the owner?",
	"What makes you furious?",
	"What makes you happy?",
	"What is your favorite sandwich?",
	"Is there anything you regret buying, and if so, what is it?",
	"What is the best thing you ever bought?",
	"If you were invisible what is something you would do?",
	"What makes you feel uncomfortable?",
	"Do you prefer cats, dogs, or neither?",
	"If there was one thing you could change about yourself, what would it be?",
	"If you were a giant, what would you like to do?",
	"What is your favorite music genre?",
	"Have you ever blamed your sibling for something you did just so that you wouldn’t get in trouble?",
	"How old were you when you got your first cell phone?",
	"When is the last time you took a shower?",
	"When is the last time you brushed your teeth?",
	"What do you like to do when you are alone?",
	"What do you like to do when you are with your friends?",
	"What was the name of your first crush?",
	"How old were you when you had your first crush?",
	"What is the best time of day for you?",
	"What is your least favorite time of the day?",
	"If you didn’t have to work, what would you do with all your time?",
	"What is your favorite possession?",
	"What is your favorite go-to website?",
	"What was the best day you ever had?",
	"What was the worst day you ever had?",
	"What is your biggest fear in life?",
	"Did you have a nickname as a child and if so, what was it?",
	"Do you prefer mushy movies or funny ones?",
	"If you only had two minutes to get out of your house, what would you grab?",
	"What is your favorite vegetable?",
	"What is your favorite fruit?",
	"Do you have a special talent and if so, what is it?",
	"Have you ever been married?",
	"What do you like to put on your toast?",
	"Do you like hot peppers?",
	"Do you prefer Facebook or Twitter?",
	"What season is your favorite?",
	"Who is your most annoying neighbor?",
	"If you could be someone else for a day who would you be?",
	"What was the name of the street you grew up on?",
	"Which do you like better, cars or trucks?",
	"What is your favorite outdoor pastime?",
	"Which do you like better, Coca-Cola or Pepsi?",
	"What is your favorite month and why?",
	"Do you like to read and if so, what is your favorite book?",
	"Have you ever met a celebrity, if so, who?",
	"Have you ever cheated to win a game?",
	"Have you ever sent a love email to your boss by accident that was meant for someone else?",
	"What food do you absolutely despise?",
	"Who is the person you are the most jealous of and why?",
	"How many different languages can you speak and what are they?",
	"Do you have any tattoos and if so, where?",
	"Have you ever been outside of the country?",
	"What is one thing your grandparents taught you how to do?",
	"Have you ever been to the opera?",
	"Do you prefer talking or texting?",
	"Have you ever had an argument with someone through text?",
	"What was the last thing you ate?",
	"Have you ever been to the zoo?",
	"What’s the scariest thing you’ve ever done?",
	"What’s your biggest regret?",
	"What’s the most childish thing you’ve ever done?",
	"What’s a bad habit you have?",
	"What’s one thing on your bucket list?",
	"What’s one thing you would do if you waked up tomorrow as the opposite sex?",
	"What’s the last dream you had? Describe.",
	"Have you ever shared a toothbrush with anyone?",
	"Have you ever told a lie and got caught?",
	"What’s one thing you like, and one thing you dislike about yourself?",
	"Have you ever done something embarrassing while drunk? Describe.",
	"What do you think about while on the toilet?",
	"If you could change one thing about your life, what would it be?",
	"What are you afraid of?",
	"Have you ever sent an inappropriate/embarrassing text to someone? Describe.",
	"Have you ever stalked someone on Facebook?",
	"Who are you most jealous of and why?",
	"What color is your underwear?",
	"What do you hate and why?",
	"ho/what is someone/something that annoys you?",
	"Have you ever been in love?",
	"What’s something in your web browsing history that you’d be embarrassed if someone saw?",
	"What would you do with your time if you didn’t have to work?",
	"What’s the worst thing that’s ever happened to you?",
	"What’s one thing you can’t live without?",
	"When’s the last time you took a shower?",
	"Have you ever lied or done something to get out of trouble?",
	"What’s the best purchase you ever made?",
	"What’s the most illegal thing you’ve ever done.",
	"What would you do with a million dollars?",
	"What do you believe in?",
	"Have you ever shared a secret you shouldn’t have, or promised you wouldn’t?",
	"What’s something you’re looking forward to and not looking forward to?",
	"You’re going #2 in a public bathroom and run out of toilet paper—what do you do?",
	"What’s something you think is absolutely disgusting?",
	"When was the last time you cried and why?",
	"If you could live anywhere, where would it be?",
	"What’s your biggest pet peeve?",
	"What do you value most in your relationships?",
	"If you could have three wishes, what would you wish for?",
	"What is your secret vice/guilty pleasure?",
	"Have you ever cheated on someone?",
	"What’s the most embarrassing thing you’ve ever done?",
	"What’s the worst gift you’ve ever received?",
	"What’s the last thing you searched on your phone?",
	"Have you ever been so drunk you blacked out?",
	"Have you ever peed your pants?",
	"Go outside holding a leash and start screaming, ‘Has anyone seen my pet alligator?’",
	"What’s the longest you’ve ever gone without a shower?",
	"What’s your grossest personal habit?",
	"What’s the one thing you wish you could unsee?",
	"If you could be reincarnated as someone in this room, who would you want to be?",
	"Who in this room do you most want to see in a bikini?",
	"Who in this room do you most want to skinny dip with?",
	"If you could be a member of the opposite sex for a day, what’s the first thing you’d do?",
	"If you had to date an animal, what kind of animal would you date?",
	"If you had to date a plant, what kind of plant would you date and why?",
	"If you had to date one of your teachers, who would it be?",
	"What would you do if you ran out of toilet paper in a public bathroom just after taking a big poop?",
	"What’s the most embarrassing thing that’s ever happened to you in public?",
	"What’s the biggest secret you’ve kept from your parents?",
	"What’s the biggest secret you’ve kept from your best friend?",
	"If you could trade places with your mom or your dad for 24 hours, who would you pick and what would you do?",
	"If you could trade places with a famous person for a day, what’s the first thing you’d do?",
	"If you could write your own law that everyone had to follow, what would it be?",
	"If you could do anything without getting caught, what would it be?",
	"What’s the one thing you’d never say to a crush?",
	"If you had five lives, what would you do that you wouldn’t do with only one?",
	"Who’s the “Bey and Jay” of your school?",
	"If you could prank anyone without getting caught, who would it be and what would you do?",
	"Who’s the queen bee of your friend group?",
	"Would you rather eat fish food or cat food?",
	"When is the last time you lied to a friend to get out of doing something?",
	"When’s the last time you lied to your parents and why?",
	"What’s the best lie you’ve ever told without anyone finding out (until now)?",
	"What would you say if you had to pretend to like a present?",
	"What animal most closely resembles you?",
	"What was your absolute worst bathroom experience?",
	"Do you currently have a crush on anyone and if so how would you describe them?",
	"What is your current crush’s personality like?",
	"What’s the one thing you’d change about your daily life?",
	"Who do you resent and why?",
	"How many people have you kissed?",
	"What’s your biggest turn-on?",
	"If you could date anyone, living or dead, who would it be?",
	"Would you date two people simultaneously if you could get away with it?",
	"Have you ever sent a sext and if so to who?",
	"Have you ever sent someone a nude selfie and if so who?",
	"Have you ever received a nude selfie and if so who was it from?",
	"Have you ever gotten mad at a friend for posting an unflattering photo of you?",
	"Who’s the last person you cyberstalked?",
	"Have you ever had a crush on a teacher and if so who?",
	"Who in this room do you think would make the best kisser?",
	"Who’s the hottest person in your entire school / company?",
	"What is the most attractive feature on the human body?",
	"What’s the funniest thing you’ve done to get a crush’s attention?",
	"What does “wife / husband material” mean to you?",
	"What’s the dirtiest thought you’ve ever had?",
	"Of the people in this room, who do you most want to make out with?",
	"What’s the first thing you’d do if you woke up one day and you were the opposite sex?",
	"What sexual activity do you consider totally off limits?",
	"Of the people in this room, who do you consider the sluttiest?",
	"What’s the most embarrassing thing your parents have caught you doing?",
	"What’s the biggest romantic fail you’ve ever experienced?",
	"What’s the weirdest thing you’ve done when you were alone?",
	"Of the people in this room, who would you feel most comfortable with naked?",
	"What’s the biggest secret you’ve ever kept from your boyfriend or girlfriend?",
	"What’s the biggest lie you’ve ever told your boyfriend or girlfriend—without getting caught?",
	"Of the people in this room, who do you most want to caress?",
	"What do you like most and least about your own appearance?",
	"What do you like most and least about your significant other’s appearance?",
	"If you could erase one past sexual experience, what would it be?",
	"What’s the craziest thing you’ve ever done to attract a crush?",
	"When’s the last time you were flat-out rejected and how did you handle it?",
	"What’s your biggest sexual fear?",
	"Of the people in this room, who would you most want to have a kid with?",
	"What’s your favorite go-to move for getting attention from the opposite sex?",
	"What would you change about your love life if you could?",
	"What’s the most flirtatious thing you’ve ever done?",
	"If you could make out with any celebrity right this second, who would it be?",
	"At what age did you first start having sexy thoughts and what prompted them?",
	"What three adjectives best describe your private parts?",
	"What does the perfect male/female body look like (from head to toe and everything in between) in your opinion?",
	"How many people can someone sleep with before you secretly judge them for their “number”?",
	"What’s the one thing you’d do in bed with someone if you had no inhibitions whatsoever?",
	"What’s sexual milestone has been most memorable for you so far?",
	"What’s the weirdest thing you’ve ever done in front of the mirror?",
	"At what age did you first inspect your private parts and how did you feel about them?",
	"What would you guess your parents’ favorite sexual position is, and why?",
	"What did you think about the first (or last) time you masturbated?",
	"What’s the most surprising thing that’s ever turned you on?",
	"What’s the grossest thing that’s come out of your body?",
	"What’s the most disgusting thing you’ve ever done?",
	"What’s the most disturbing fantasy or dream you’ve ever had?",
	"What’s the most awkward experience you’ve had with a crush?",
	"What’s the funniest thing you’ve ever said to someone you had a crush on?",
	"What’s the cruelest thing you’ve ever done to a boyfriend or girlfriend?",
	"What time of day do you feel most aroused and what do you usually do about it?",
	"What’s the funniest urge you’ve ever had?",
	"What’s the biggest sexual regret you have?",
	"How old were you when your parents sat you down for “the talk” and what did they say (or not say) about “the birds and the bees”?",
	"What’s the biggest dating disappointment you’ve experienced so far?",
	"Do you ever catch yourself thinking about doing it with someone of the same sex?",
	"How far would you go to land the guy or girl of your dreams?",
	"What is the stupidest thing you have ever done?",
	"Name a Guy/Girl whom you want to Date.",
	"Tell 5 names of your crushes.",
	"What would you do with a million dollars if you ever won the lottery?",
	"What is the silliest thing you have an emotional attachment to?",
	"Say some disgusting habit’s you have?",
	"Tell me about your first kiss.",
	"Who here would you like to propose if you get a chance?",
	"Who are you jealous of?",
	"What’s your ex-girlfriend/boyfriend name?",
	"What is the most embarrassing moment of your life?",
	"Describe something about your date?",
	"What is something you have stolen?",
	"What is your special talent?",
	"How many cigarettes do you smoke a day?",
	"Who look more sexy among us?",
	"Say 5 bad habits you have?",
	"What are you most afraid of?",
	"Say 5 negatives about me!",
	"What do you like in me?",
	"Future wife/husband qualities.",
	"How many boyfriends/Girlfriends do you have?",
	"what is your weight?",
	"Tell 5 secrets of yours?",
	"what is your favorite place to spend time?",
	"Whom do you hate the most?",
	"what is your age?",
	"Did you watch XXX Videos?",
	"whom you love the most?",
	"What is the scariest dream you have ever had?",
	"Why did you break up with your last boyfriend or girlfriend?",
	"Most hated person in the world?",
	"Have you ever let someone take the blame for something you did?",
	"What lie have you told that hurt someone?",
	"What secret about yourself did you tell someone in confidence and then they told a lot of other people?",
	"At what time do you wake up in the morning?",
	"How many Boys/Girls have given you love letters?",
	"What you do when you are alone at home?",
	"Say something about me!",
	"How many times a day you eat?",
	"Which kind of food you like the most?",
	"Favorite Place you like to visit?",
	"What is the most embarrassing thing your parents have caught you doing?",
	"What are you most self-conscious about?",
	"What is the most embarrassing picture of you?",
	"What would you do if you were the opposite sex for a month?",
	"What is the most expensive thing you have stolen?",
	"What is the most childish thing you still do?",
	"What do most of your friends think about you that is totally untrue?",
	"Who here would you most like to make out with?",
	"Have you ever cheated or been cheated on?",
	"What is the meanest you have been to someone that didn’t deserve it?",
	"What is something that people think you would never do but you have?",
	"What was the worst encounter you had with a police officer?",
	"Tell me about your most awkward date.",
	"What is your deepest darkest fear?",
	"Where is the strangest place you have peed?",
	"Who is the person you most regret kissing?",
	"Have you ever crapped your pants since you were a child?",
	"When was the most inappropriate time you farted?",
	"What is the most embarrassing thing in your room?",
	"When was the last time you peed in bed?",
	"Who is the sexiest person here?",
	"What is the grossest thing that has come out of your body?",
	"What terrible thing have you done that you lied to cover up?",
	"Who have you loved but they didn’t love you back?",
	"What is something that you have never told anyone?",
	"What is the most disgusting habit you have?",
	"What was the cruelest joke you played on someone?",
	"What is the most embarrassing thing you have put up on social media?",
	"What bad thing have you done that no one else found out about?",
	"What was the most awkward romantic encounter you have had?",
	"What is the grossest thing you have had in your mouth?",
	"Tell me about the last time someone unexpectedly walked in on you while you were naked.",
	"What is the most embarrassing nickname you have ever had?",
	"What is the biggest lie you have ever told?",
	"What is the most embarrassing photo you have on your phone?",
	"Describe your most recent romantic encounter.",
	"What is the weirdest thing you have done for a boyfriend or girlfriend?",
	"Who here has the nicest butt?",
	"What is your biggest regret?",
	"Is it true that you (whatever you or the group suspects they do / did)?",
	"When was the last time you picked your nose without a tissue?",
	"What do you really hope your parents never find out about?",
	"Tell us your most embarrassing vomit story.",
	"Tell me something you don’t want me to know.",
	"Have you ever made out with someone here?",
	"What is the airspeed velocity of an unladen swallow?",
	"What have you done that people here would judge you most for doing?",
	"What would you do if you were the opposite gender for a day?",
	"Who is your crush?",
	"What was the last thing you searched for on your phone?",
	"If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
	"Have you ever walked in on your parents doing it?",
	"After you've dropped a piece of food, what's the longest time you've left it on the ground and then ate it?",
	"Have you ever tasted a booger?",
	"Have you ever played Cards Against Humanity with your parents?",
	"What's the first thing you would do if you woke up one day as the opposite sex?",
	"Have you ever peed in the pool?",
	"Who do you think is the worst dressed person in this room?",
	"Have you ever farted in an elevator?",
	"True or false? You have a crush on [fill in the blank].",
	"Of the people in this room, who do you want to trade lives with?",
	"What are some things you think about when sitting on the toilet?",
	"Did you have an imaginary friend growing up?",
	"Do you cover your eyes during a scary part in a movie?",
	"Have you ever practiced kissing in a mirror?",
	"Did your parents ever give you the “birds and the bees” talk?",
	"What is your worst habit?",
	"Has anyone ever walked in on you when going #2 in the bathroom?",
	"Have you ever had a wardrobe malfunction?",
	"Have you ever walked into a wall?",
	"Do you pick your nose?",
	"Do you sing in the shower?",
	"Have you ever peed yourself?",
	"What was your most embarrassing moment in public?",
	"Have you ever farted loudly in home?",
	"Do you ever talk to yourself in the mirror?",
	"You’re in a public restroom and just went #2, then you realized your stall has no toilet paper. What do you do?",
	"What would be in your web history that you’d be embarrassed if someone saw?",
	"Have you ever tried to take a sexy picture of yourself?",
	"Do you sleep with a stuffed animal?",
	"Do you drool in your sleep?",
	"Do you talk in your sleep?",
	"Who is your secret crush?",
	"Do you think [fill in the name] is cute?",
	"Who do you like the least in this room and why?",
	"What does your dream boy or girl look like?",
	"What is your go-to song for the shower?",
	"Who is the sexiest person in this room?",
	"How would you rate your looks on a scale of 1 to 10?",
	"Would you rather have sex with [insert name] in secret or not have sex with that person but everyone thinks you did?",
	"What don't you like about me?",
	"What color underwear are you wearing right now?",
	"What was the last thing you texted?",
	"If you were rescuing people from a burning building and you had to leave one person behind from this room, who would it be?",
	"Do you think you'll marry your current girlfriend/boyfriend?",
	"How often do you wash your undergarments?",
	"Have you ever tasted ear wax?",
	"Have you ever farted and then blamed someone else?",
	"Have you ever tasted your sweat?",
	"What is the most illegal thing you have ever done?",
	"Who is your favorite? Mom or Dad?",
	"Would you trade your sibling in for a million dollars?",
	"Would you trade in your dog for a million dollars?",
	"If you were allowed to marry more than one person, would you? Who would you choose to marry?",
	"Would you rather lose your sex organs forever or gain 200 pounds?",
	"Would you choose to save 100 people without anyone knowing about it or not save them but have everyone praise you for it?",
	"If you could only hear one song for the rest of your life, what would it be?",
	"If you lost one day of your life every time you said a swear word, would you try not to do it?",
	"Who in this room would be the worst person to date? Why?",
	"Would you rather live with no internet or no A/C or heating?",
	"If someone offered you $1 million dollars to break up with your girlfriend/boyfriend, would you do it?",
	"If you were reborn, what decade would you want to be born in?",
	"If you could go back in time in erase one thing you said or did, what would it be?",
	"Has your boyfriend or girlfriend ever embarrassed you?",
	"Have you ever thought about cheating on your partner?",
	"If you could suddenly become invisible, what would you do?",
	"Have you ever been caught checking someone out?",
	"Have you ever waved at someone thinking they saw you when really they didn't? What did you do when you realized it?",
	"What's the longest time you've stayed in the bathroom, and why did you stay for that long?",
	"What's the most unflattering school picture of you?",
	"Have you ever cried because you missed your parents so much?",
	"Would you rather be caught picking your nose or picking a wedgie?",
	"Describe the strangest dream you've ever had. Did you like it?",
	"Have you ever posted something on social media that you regret?",
	"What is your biggest fear?",
	"Do you pee in the shower?",
	"Have you ever ding dong ditched someone?",
	"The world ends next week and you can do anything you want (even if it's illegal). What would you do?",
	"Would you wear your shirt inside out for a whole day if someone paid you $100?",
	"What is the most childish thing that you still do?",
	"Tell us about a time you embarrassed yourself in front of a crush.",
	"Who is one person you pretend to like, but actually don’t?",
	"What children’s movie could you watch over and over again?",
	"Do you have bad foot odor?",
	"Do you have any silly nicknames?",
	"When was the last time you wet the bed?",
	"How many pancakes have you eaten in a single sitting?",
	"Have you ever accidentally hit something with your car?",
	"If you had to make out with any Disney character, who would it be?",
	"Have you ever watched a movie you knew you shouldn’t?",
	"Have you ever wanted to try LARP (Live Action Role-Play)?",
	"What app on your phone do you waste the most time on?",
	"Have you ever pretended to be sick to get out of something? If so, what was it?",
	"What is the most food you’ve eaten in a single sitting?",
	"Do you dance when you’re by yourself?",
	"Would you have voted for or against Trump?",
	"What song on the radio do you sing with every time it comes on?",
	"Do you own a pair of footie pajamas?",
	"Are you scared of the dark?",
	"What ‘As seen on TV’ product do you secretly want to buy?",
	"Do you still take bubble baths?",
	"If you were home by yourself all day, what would you do?",
	"How many selfies do you take a day?",
	"What is something you’ve done to try to be ‘cooler’?",
	"When was the last time you brushed your teeth?",
	"Have you ever used self tanner?",
	"What do your favorite pajamas look like?",
	"Do you have a security blanket?",
	"Have you ever eaten something off the floor?",
	"Have you ever butt-dialed someone?",
	"Do you like hanging out with your parents?",
	"Have you ever got caught doing something you shouldn’t?",
	"What part of your body do you love and which part do you hate?",
	"Have you ever had lice?",
	"Have you ever pooped your pants?",
	"What was the last rate-R movie you watched?",
	"Do you lick your plate?",
	"What is something that no one else knows about you?",
	"Do you write in a diary?",
	"What is the worst date you’ve ever been on?",
	"Have you ever had a crush on a friend’s boyfriend/girlfriend?",
	"If you had to make out with a boy at school, who would it be?",
	"Would you rather go for a month without washing your hair or go for a day without wearing a bra?",
	"Have you ever asked someone out?",
	"Have you ever had a crush on a person at least 10 years older than you?",
	"Who is the worst kisser you’ve kissed?",
	"What size is your bra?",
	"Do you wear tighty whities or granny panties?",
	"Do you ever admire yourself in the mirror?",
	"Has a crush ever found out you liked them and turned you down?",
	"Have you ever been stood up on a date?",
	"What’s the most embarrassing thing you’ve done regarding your crush?",
	"Do you secretly love Twilight?",
	"Have you ever wanted to be a cheerleader?",
	"Who is the hottest? Hagrid, Dumbledore, or Dobby?",
	"If you could marry any celebrity, who would it be?",
	"What do you do to get yourself ‘sexy’?",
	"Who is your current crush?",
	"What hairstyle have you always wanted, but never been willing to try?",
	"What’s the most embarrassing thing you’ve said or done in front of someone you like?",
	"Who is your celebrity crush?",
	"If you could change one thing about your body, what would it be?",
	"Who was your first kiss? Did you like it?",
	"If you could be another girl at our school, who would you be?",
	"Would you kiss a guy on the first date? Would you do more than that?",
	"Who are the top 5 cutest guys in our room? Rank them.",
	"How many kids do you want to have in the future?",
	"Who do you hate the most?",
	"If you could go out on a date with a celebrity, who would it be?",
	"If you were stranded on a deserted island, who would you want to be stranded with from our school?",
	"Have you ever flirted with your best friend’s siblings?",
	"Have you ever been dumped? What was the reason for it?",
	"Jock, nerd, or bad guy?",
	"Have you ever had a crush on friend's boyfriend?",
	"Who is your first pick for prom?",
	"What's the sexiest thing about a guy?",
	"What's the sexiest thing about a girl?",
	"What's one physical feature that you would change on yourself if you could?",
	"Would you rather be a guy than a girl? Why?",
	"Describe your dream career.",
	"If you could eat anything you wanted without getting fat, what would that food be?",
	"If you had to do a gameshow with someone in this room, who would you pick?",
	"Would you go a year without your phone if it meant you could marry the person of your dreams?",
	"You are going to be stuck on a dessert island and you can only bring five things. List them.",
	"If you could only wear one hairstyle for the rest of your life, would you choose curly hair or straight hair?",
	"You have to give up one makeup item for the rest of your life. What is it?",
	"Would you date someone shorter than you?",
	"If someone paid you $1000 to wear your bra outside your shirt, would you do it?",
	"Who would you hate to see naked?",
	"How long have you gone without a shower?",
	"If you could only text one person for the rest of your life, but you could never talk to that person face to face, who would that be?",
	"How long have you gone without brushing your teeth?",
	"What's one thing you would never eat on a first date?",
	"What have you seen that you wish you could unsee?",
	"If you could be reincarnated into anyone's body, who would you want to become?",
	"If you switched genders for the day, what would you do?",
	"What's one food that you will never order at a restaurant?",
	"What's the worst weather to be stuck outside in if all you could wear was a bathing suit?",
	"If your car broke down in the middle of the road, who in this room would be the last person you would call? Why?",
	"What's the most useless piece of knowledge you know?",
	"What did you learn in school that you wish you could forget?",
	"Is it better to use shampoo as soap or soap as shampoo?",
	"If you ran out of toilet paper, would you consider wiping with the empty roll?",
	"What would be the worst part about getting pantsed in front of your crush?",
	"If you could only use one swear word for the rest of your life, which one would you choose?",
	"What's the best thing to say to your friend that would be the worst thing to say to your crush?",
	"Who do you think is the Beyonce of the group?",
	"Would you rather eat dog food or cat food?",
	"If you had nine lives, what would you do that you wouldn't do now?",
	"If you could play a prank on anyone without getting caught, who would you play it on?",
	"What would the prank be?",
	"Have you ever pretended to like a gift? How did you pretend?",
	"Would you rather not shower for a month, or eat the same meal everyday for a month?",
	"What animal most closely resembles your eating style?",
	"If you could choose to never sweat for the rest of your life or never have to use the bathroom, which would you choose?",
	"If you could spend every waking moment with your gf or bf, would you?",
	"Truth or Dare Questions That Will Test Your Friendship",
	"If your crush told you he liked your best friend, what would you do?",
	"What if you best friend told you that she liked your crush?",
	"If you knew your friend's boyfriend was cheating on her, what would you do?",
	"Have you ever told a lie about your best friend to make yourself look better?",
	"What was your first impression of [fill in the name of a person in the room]?",
	"If you had to date someone else's boyfriend, who would it be?",
	"Who's hotter? You or your friend?",
	"Have you ever shared your friend's secret with someone else?",
	"Rate everyone in the room from 1 to 10, with 10 being the hottest.",
	"Would you share a toothbrush with you best friend?",
	"Rate everyone in the room from 1 to 10, with 10 being the best personality.",
	"Have you ever ignored a friend's text. Why did you do it?",
	"Have you ever lied to your best friend?",
	"Would you let a friend cheat on a test?",
	"If your friend asked you to lie for her and you knew you would get in trouble, would you do it?",
	"If one of your friends was cheating with your other friend's boyfriend, what would you do?",
	"Would you ditch your friends if you could become the most popular girl in school?",
	"If you had to choose, who would you stop being friends with?",
	"Name one thing you would change about each person in this room.",
	"If you had to trade your friend in for the celebrity crush of your dreams, which friend would you choose.",
	"What was your first impression of your best friend's boyfriend?",
	"What do you think about him now?",
	"Have you ever thought about ditching your friend for a boy?",
	"If someone asked you what your best friend is like, how would you describe her?",
	"You win a trip and are allowed to bring two people. Who do you pick?",
	"On an overnight trip, would you rather share a bed with your best friend or her boyfriend?",
	"If you could swap one physical feature with your best friend, what would that be?",
	"Have you ever told a secret you were told to keep?",
	"If your best friend had B.O., would you tell her?",
	"What is the most annoying thing about your best friend?",
	"Who do you think you friend should date instead of her current boyfriend?",
	"If she doesn't have a boyfriend, who do you think she should date?",
	"Do you think your friend's boyfriend is hot?",
	"Would you hook up with him if you knew she would never find out?",
	"Have you ever ditched your friend for a boy?",
	"If your friend and your boyfriend were both dying in front of you, who would try to save first?",
	"Do you currently have a crush on anyone?",
	"Describe what your crush looks like.",
	"What is your crush's personality like?",
	"Is there anything about your life you would change?",
	"Who do you hate and why?",
	"What's your biggest pet peeve?",
	"What's your biggest turn-on?",
	"If you could date anyone in the world, who would you date?",
	"Would you rather be skinny and hairy or fat and smooth?",
	"Who would you ask to prom if you could choose anyone?",
	"Describe your perfect date.",
	"Would you ever date two people at once if you could get away with it?",
	"You have to delete every app on your except for five. Name the five you would keep.",
	"Have you ever sent out a nude snapchat?",
	"Have you ever received a nude selfie? Who was it from?",
	"What was your reaction? Like or dislike?",
	"Have you ever gotten mad at a friend for posting an unflattering picture of you?",
	"Have you ever had a crush on a teacher?",
	"Who do you think would make the best kisser? (List a few people for them to choose.)",
	"Have you ever sent someone the wrong text?",
	"Have you ever cursed at your parents? Why?",
	"Who do you think is the cutest person in our room?",
	"What is the most attractive feature on a person?",
	"What the biggest deal breaker for you?",
	"How far would you go on a first date?",
	"Have you ever regretted something you did to get a crush's attention?",
	"Would you ever be mean to someone if it meant you could save your close friend from embarrassment?",
	"Of the people at our school, who do you think would make the best president?",
	"If we didn't have a dress code, what would you wear to school that you can't wear now?",
	"Describe what makes someone husband or wife material.",
	"If you could make $1 million, would you drop out of school?",
	"What's one thing you do that you don't want anyone to know about?",
	"Do you frequently stalk anyone on social media? Who?",
	"If you had to choose between dating someone ugly who was good in bed or dating someone hot who was bad in bed, which would you choose?",
	"If you could be invisible, who would you spy on?",
	"Who are the top 5 hottest girls at our room?",
	"Who in this room would you make out with?",
	"If you could date of your bro's girlfriends, who would it be?",
	"What your favorite body part?",
	"When was the last time you flexed in the mirror?",
	"Describe your perfect partner.",
	"Blonde or brunette?",
	"What turns you on the most?",
	"If your parents hated your girlfriend, would you dump her?",
	"If your girlfriend hated your best friend, what would you do?",
	"Who is your biggest celebrity crush?",
	"Would you take steroids?",
	"Have you ever had a crush on a friend's girlfriend?",
	"Who do you think is the hottest in our group?",
	"What is your biggest turn-off?",
	"Have you ever been rejected by someone?",
	"If you had to choose between being poor and smart or being rich and dumb, what would you choose?",
	"What have you lied to your partner about?",
	"Have you ever cheated on your partner?",
	"Would you go out with an older woman?",
	"Do you have a crush on someone from another school?",
	"Boxers or briefs?",
	"When was the last time you cried?",
	"If you could make out with someone else's girl, who would it be?",
	"If every time you checked out a girl's body, you would gain 5 pounds, how often would you do it?",
	"Have you ever lied about your age?",
	"Have you ever fallen in love at first sight?",
	"If a girl you didn't like had a crush on you, how would you act around her?",
	"What if she was your friend?",
	"What would you do if you found out your girlfriend liked someone else?",
	"If we formed a boy band, who here would make the best lead singer?",
	"Who do you want to make out with the most?",
	"If you had to flash just one person in this room, who would it be?",
	"If you haven't had your first kiss yet, who in this room do you want to have your first kiss with?",
	"Of the people in this room, who would you go out with?",
	"Who here do you think is the best flirt?",
	"Who has the best smile?",
	"Who has the cutest nose?",
	"How about prettiest eyes?",
	"Who's the funniest in this room?",
	"What's one thing you would never do in front of someone you had a crush on?",
	"How often do you check yourself out in the mirror when you're on a date?",
	"Who here do you think would be the best kisser?",
	"Who has the best dance moves?",
	"If you could have one physical feature of someone in this room, what would that be?",
	"What is your wildest fantasy?",
	"How far would you go with someone you just met and will never see again?",
	"Rate me on a scale of 1 to 10, with 10 being the hottest.",
	"If I was a food, what would I be, and how would you eat me?",
	"Would you choose a wild, hot relationship or a calm and stable one?",
	"If you had one week to live and you had to marry someone in this room, who would it be?",
	"If you only had 24 hours to live and you could do anything with anyone in this room, who would it be and what would you do with that person?",
	"And biggest turn-off?",
	"Would you go out with me if I was the last person on earth?",
	"What's the most flirtatious thing you've ever done?",
	"What's the sexiest thing about [fill in the name of a person in the room]?",
	"If you could go on a romantic date with anyone in this room, who would you pick?",
	"If you had to delete one app from your phone, what would it be?",
	"What is your greatest fear in a relationship?",
	"Go around the room and say one positive and one negative thing about each person.",
	"What is one disturbing fact I should know about you?",
	"Have you ever smoked?",
	"Have you ever tried drugs?",
	"What about alcohol?",
	"What's the craziest thing you've done while under the influence?",
	"If you were trapped for three days on an island, who are three people in this room you would bring with you and why?",
	"Would you go to a nude beach?",
	"Who's the most annoying person in this room?",
	"If you had to marry someone in this room, who would it be?",
	"Do you have hidden piercings or tattoos?",
	"How long was your longest relationship?",
	"If you could have one celebrity follow you on Instagram, who would that be?",
	"You have to delete 5 people on Instagram. Name them.",
	"Do you want to get married one day?",
	"Do you want to have kids? How many?",
	"Would you ever get into a long distance relationship?",
	"What would you do if you found out you flunked school?",
	"If you're girlfriend or boyfriend broke up with you at school, what would you do?",
	"If you had the power to fire one teacher, who would it be?",
	"Basketball, baseball, or football?",
	"What was your first job?",
	"If you don't have one yet, where would you want to work?",
	"How many hours would you spend online if you didn't have school or homework?",
	"How tall do you want to be?",
	"What's your biggest fear about college?",
	"What are you most excited about?",
	"Would you want your best friend to go to the same college as you?",
	"Would you want your current boyfriend or girlfriend to go to the same college as you?",
	"Who do you think is the hottest celebrity?",
	"What's you dream job?",
	"What was a rumor that went around about you?",
	"Have you ever failed a exam?",
	"If you had the power to fire one teacher, who would that be?",
	"If you could plan a room prank knowing you'll never get caught, what would the prank be?",
	"Have you ever had a crush on a teacher? Who?",
	"Who would you take to prom?",
	"Have you ever made out at school?",
	"Who would you never ever want to sit next to in room?",
	"Have you ever been late to exam?",
	"What's the most embarrassing thing you've ever done in front of a teacher?",
	"Have you ever stuck gum under a desk?",
	"What do you think is better: tests or essays?",
	"Have you ever eaten lunch by yourself? Why?",
	"If you had to choose one food for the rest of your life, what food would it be?",
	"If you wanted to make out on campus, where would you do it?",
	"Have you ever gotten into a fight on school grounds?",
	"What was the worst score you’ve ever gotten on a test?",
	"Have you ever gotten detention or been suspended?",
	"If you were invisible, would you sneak a peak in the other locker room?",
	"If so, who would you be hoping to see?",
	"Who's the hottest teacher at our school?",
	"If you had to take a person from another grade to prom, who would that be?",
	"Have you ever flashed someone?",
	"Have you ever sexted anyone?",
	"Have you ever been to a nudist beach? Would you consider going?",
	"Would you ever consider posing for Playboy?",
	"Who has seen you without clothes on?",
	"Have you ever seen a naughty magazine?",
	"Have you ever sent a nude selfie? Who would you send it to?",
	"Have you ever searched for something dirty on the internet?",
	"Who do you most want to sleep with, out of everyone here?",
	"What's your favorite body part on your partner?",
	"Have you ever been attracted to the same sex?",
	"When and where was your first kiss? Who was it with?",
	"When did you lose your virginity and who did you lose it with?",
	"What's your ultimate sexual fantasy?",
	"Would you go out with an older guy? How old is too old?",
	"Do you sleep in the nude?",
	"How much money would we have to pay you for you to agree to flash your boobs?",
	"Have you ever been in a friends with benefits situation?",
	"If you had to go skinny dipping with someone, who in this room would you choose?",
	"If I paid you $100, would you wear your sexiest clothes to room?",
];

function getRandomArrayElement(arr) {
	//Minimum value is set to 0 because array indexes start at 0.
	var min = 0;
	//Get the maximum value my getting the size of the
	//array and subtracting by 1.
	var max = (arr.length - 1);
	//Get a random integer between the min and max value.
	var randIndex = Math.floor(Math.random() * (max - min)) + min;
	//Return random value.
	return arr[randIndex];
}

exports.assistantdemo = functions.https.onRequest((req, res) => {
	const query = req.query.query;
	if (query.length > 0) {
		assistant.assist(query)
			.then(({
				text
			}) => {
				res.json({
					"res": text
				});
			});
	}

});

exports.tod = functions.https.onRequest((req, res) => {
	const query = req.query.query;
	var receiver = query.split(" ");

	var qn = getRandomArrayElement(questions);

	res.send(receiver[1] + ": " + qn)
});